server:
  port: 8100
spring:
  application:
    name: delivery-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true